services:
  realsy-redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
      
  realsy-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 345543
      POSTGRES_DB: postgresDB
    ports:
      - "5433:5432"