services:
  chathub.redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  realestateagency.api:
    image: realestateagency.api
    build:
      context: .
      dockerfile: Dockerfile
